#如果你不知道数据库对应的配置，那么只需要改host,port,database,user,passwd即可
Mysql:
  Enable: false
  host: 127.0.0.1
  port: 3306
  database: ChunkWorld
  user: Adear
  passwd: '123456'
  ssl: false
  HikariCP: true
#redis数据库配置
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
World: "/home"
Resource: "chunkWorld"
Location: "world,2.5,64.0,8.0,-90,0"
#lore第一行必须有玩家名字才能对应使用
item:
  material: "STRUCTURE_VOID"
  #-1代表没有，代表不启用，使用原版的
  customModelData: -1
#日期判断，用于重启时自动刷新资源世界
date: "2024-07-10"