#如果你不知道数据库对应的配置，那么只需要改host,port,database,user,passwd即可
Mysql:
  host: 127.0.0.1
  port: 3306
  database: ChunkWorld
  user: Adear
  passwd: '123456'
  ssl: false
  HikariCP: true
#redis数据库配置
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
#每个服都应该有一个出生点，用作应急
Location: "world,2.5,64.0,8.0,-90,0"
serverName: "home"
Baoxiang:
  world:
    Ymin: -54
    Ymax: -1
  #指令默认控制台执行
    commands:
      - "say hello"
  nether:
    Ymin: 10
    Ymax: 30
    commands:
      - "say hello"