main: # inject
name: # inject
version: ${version}
authors:
  - dongzh1
  - xbaimiao
api-version: "1.20"
folia-supported: false
update-info: # inject
depend-list: # inject
relocate: # inject
kotlin-version: # inject
#world用于大厅，新建一个世界和地狱末地相连成资源
