package com.dongzh1.chunkworld.basic

import org.bukkit.block.Biome
import org.bukkit.block.Biome.*

object Biome {
    val Biome.chinese get() = let {
        when (this) {
            OCEAN -> "海洋"
            PLAINS -> "平原"
            DESERT -> "沙漠"
            WINDSWEPT_HILLS -> "风袭山丘"
            FOREST -> "森林"
            TAIGA -> "针叶林"
            SWAMP -> "沼泽"
            MANGROVE_SWAMP -> "红树林沼泽"
            RIVER -> "河流"
            NETHER_WASTES -> "下界荒地"
            THE_END -> "末地"
            FROZEN_OCEAN -> "冰冻海洋"
            FROZEN_RIVER -> "冰冻河流"
            SNOWY_PLAINS -> "雪原"
            MUSHROOM_FIELDS -> "蘑菇岛"
            BEACH -> "沙滩"
            JUNGLE -> "丛林"
            SPARSE_JUNGLE -> "稀疏丛林"
            DEEP_OCEAN -> "深海"
            STONY_SHORE -> "石滩"
            SNOWY_BEACH -> "雪滩"
            BIRCH_FOREST -> "白桦林"
            DARK_FOREST -> "黑森林"
            SNOWY_TAIGA -> "雪地针叶林"
            OLD_GROWTH_PINE_TAIGA -> "巨型松针叶林"
            WINDSWEPT_FOREST -> "风袭森林"
            SAVANNA -> "热带草原"
            SAVANNA_PLATEAU -> "热带草原高地"
            BADLANDS -> "坏地"
            WOODED_BADLANDS -> "林地坏地"
            SMALL_END_ISLANDS -> "小末地岛屿"
            END_MIDLANDS -> "末地中部"
            END_HIGHLANDS -> "末地高地"
            END_BARRENS -> "末地荒原"
            WARM_OCEAN -> "温暖海洋"
            LUKEWARM_OCEAN -> "微暖海洋"
            COLD_OCEAN -> "寒冷海洋"
            DEEP_LUKEWARM_OCEAN -> "温水深海"
            DEEP_COLD_OCEAN -> "深寒海洋"
            DEEP_FROZEN_OCEAN -> "深冰冻海洋"
            THE_VOID -> "虚空"
            SUNFLOWER_PLAINS -> "向日葵平原"
            WINDSWEPT_GRAVELLY_HILLS -> "风袭砾石山丘"
            FLOWER_FOREST -> "花海森林"
            ICE_SPIKES -> "冰刺平原"
            OLD_GROWTH_BIRCH_FOREST -> "巨型白桦林"
            OLD_GROWTH_SPRUCE_TAIGA -> "巨型云杉针叶林"
            WINDSWEPT_SAVANNA -> "风袭热带草原"
            ERODED_BADLANDS -> "侵蚀坏地"
            BAMBOO_JUNGLE -> "竹林"
            SOUL_SAND_VALLEY -> "灵魂沙谷"
            CRIMSON_FOREST -> "绯红森林"
            WARPED_FOREST -> "诡异森林"
            BASALT_DELTAS -> "玄武岩三角洲"
            DRIPSTONE_CAVES -> "钟乳石洞穴"
            LUSH_CAVES -> "繁茂洞穴"
            DEEP_DARK -> "深暗之地"
            MEADOW -> "草甸"
            GROVE -> "林地"
            SNOWY_SLOPES -> "雪坡"
            FROZEN_PEAKS -> "冰封山峰"
            JAGGED_PEAKS -> "锯齿山峰"
            STONY_PEAKS -> "石质山峰"
            CHERRY_GROVE -> "樱花林地"
            CUSTOM -> "自定义"
        }
    }
}